DFE-Digital/teacher-cpd-dataform

- definitions/marts/looker_studio_marts/ecf/ls_ecf_declaration_progress_tracker.sqlx
> Omitted comma

- definitions/marts/looker_studio_marts/ecf/ls_ecf_induction_lp_dedupe_start_decs.sqlx
Made a mistake earlier on the join between declarations and deduped induction records.
> Changed the join in the LP ECF Dedupe

- definitions/dfe_analytics_dataform.js
New field streaming through 'cohort_id' in participant_declarations. Have added it to pipeline so that it can be handled correctly.
> Adding cohort_id to participant_declarations in Dataform Pipeline

- package-lock.json
- package.json
Update of dfe-analytics-dataform to latest version 1.12.0
> Update of dfe-analytics-dataform to version 1.12.0.

- definitions/dfe_analytics_dataform.js
Added field 'cohort_changed_after_payments_frozen' to participant_profiles section of dfe_analytics_dataform as it is a new unhandled field
> Added unhandled field 'cohort_changed_after_payments_frozen'

- definitions/dfe_analytics_dataform.js
- definitions/marts/looker_studio_marts/ecf/ls_ecf_reg_school_cohorts.sqlx
Just minor changes changing the capitalisation in output fields and added a new field coming through the pipeline.
> Field output changes + pipeline update

- definitions/marts/tad_marts/tad_ecf_induction_records.sqlx
Adding the field + description so that TAD can see it in their tables.
> Adding cohort_rolled_over to TAD dataset

- definitions/operations/delete_inactive_datasets.sqlx
Based on BAT SQL code to delete inactive datasets of more than 30 days
> Added delete_inactive_datasets

- definitions/dfe_analytics_dataform.js
Added payments_frozen_at field to cohorts entity
> Added payments_frozen_at field to cohorts entity

- definitions/dfe_analytics_dataform.js
Have added a custom event in the DfE analytics package to handle API requests streaming through.
> API Request Custom Event Creation

- definitions/declarations/static_tables/declaration_states_latest_cpd_archive.sqlx
- definitions/dfe_analytics_dataform.js
Have archived the table and created a declaration to point to the archived copy and have removed the code from the analytics package.
> Remove Declaration States Latest from pipeline

- definitions/declarations/static_tables/npq_2025_expected_volumes.sqlx
- definitions/declarations/static_tables/npq_2025_price_per_participant.sqlx
- definitions/declarations/static_tables/npq_average_declaration_conversion_rates.sqlx
- definitions/declarations/static_tables/npq_average_declaration_conversion_rates_starts.sqlx
- definitions/marts/looker_studio_marts/npq/ls_npq_contract_management.sqlx
- definitions/marts/looker_studio_marts/npq/ls_npq_contract_management_2025.sqlx
This PR contains all of the required elements to be able to produce the 2025 Contract Management Dashboard.
> Addition of LS Mart for NPQ Contract Management 2025

- definitions/marts/bigquery_marts/npq/npq_enrolments.sqlx
Existing logic is causing duplicates leading to assertion errors.
> Change to partition by used to calculate application_trn

- definitions/marts/looker_studio_marts/ls_page_dates.sqlx
- definitions/marts/looker_studio_marts/ls_pageview_next_steps.sqlx
Also move Looker Studio Sankey diagram workaround out of custom field into Dataform
> Add ECF 2.0 and NPQ to web analytics

- definitions/declarations/static_tables/ecf_mentor_backfill_grant_funding_paid_24.sqlx
- definitions/marts/looker_studio_marts/ecf/ls_ecf_mentor_backfill_grant_funding.sqlx
The assurance team wanted to exclude mentors paid for the same declarations last year. I've added logic to exclude those users and their declarations and I've added logic to classify why participants aren't eligible for funding.
> Updated Mentor Backfill Mart

- definitions/marts/looker_studio_marts/ls_page_dates.sqlx
Useful when combined with number_of_unique_views to calculate view per viewer rate reliably
> Add number_of_authenticated_views

- definitions/declarations/static_tables/npq_2025_allocated_volumes_values.sqlx
- definitions/marts/looker_studio_marts/npq/ls_npq_contract_management_2025.sqlx
Changing  data source in contract management dashboard after CMs confirmed the allocated funding and volumes of participants for 2025
> Updating CM allocated volumes and values

- definitions/declarations/dfe-analytics-dataform/declare_ecf2_sandbox_dfe_analytics_dataform_tables.js
- definitions/marts/looker_studio_marts/ls_ecf_api_monitoring.sqlx
- includes/functions.js
I've added the new ECF2 Sandbox API calls into the primary ECF API monitoring mart. I've also created a function to extract the name of the lead provider from the lead provider field which is an array of strings.
> Incorporated ECF2 Sandbox API calls into main ECF API Mart

- definitions/marts/itt_mentor_marts/itt_mentor_claims_have_unexpected_status.sqlx
- definitions/marts/itt_mentor_marts/mentors_and_providers_itt_ecf_combined.sqlx
Two new statuses are streaming through, these have been defined and included.
> Updated ITT/ECF marts to accommodate new statuses

- definitions/marts/looker_studio_marts/ecf/ls_ecf_kpi_correction_cube.sqlx
- definitions/marts/looker_studio_marts/npq/ls_npq_kpi_correction_cube.sqlx
Exclude some corrections that are automated jobs, and distinguish between corrections which are changes to values and corrections which are setting values for the first time
> Corrections mart refinements
